import mongoose from "mongoose";

// Create a Mongoose schema for the xlData subdocument
const xlDataSchema = new mongoose.Schema({
    "Notice ID": String,
    "DATE": String,
    "ACCOUNT": Number,
    "CARDNO": String,
    "FPR_NAME": String,
    "FPR_LD_LIN": String,
    "FPR_MOB": Number,
    "EMBONAME": String,
    "ADDRESS1": String,
    "ADDRESS2": String,
    "CITY": String,
    "STATE": String,
    "PINCODE": Number,
    "NEWRISKREGION": String,
    "NEW_CURR BAL": String,
    "RISKCLASS": String,
    "BLOCK1": String,
    "BLOCK2": String,
    "ZONE": String,
    "SENDER": String,
    "BKT": Number,
    "MOBILEPHONE_HOME": Number,
    "TRIGGER": String,
    "ACTIVITY": String,
    "STAGE": String,
    "DPI_Amount": String,
    "Cur Bal": String,
    "Notice Amount(Cur bal+DPI)": String,
    "E-mail": String,
    "CASE No": String,
    "REF_NO": String,
    "NAME_OF_ARBITRATOR": String,
    "ADDRESS_OF_ARBITRATOR1": String,
    "ADDRESS_OF_ARBITRATOR2": String,
    "CITY_ARB": String,
    "PINCODE_ARB": String,
    "DATE_ARB": String,
    "TIME_ARB": String,
    "MEETING_LINK": String,
    "MEETING_PASSWORD": String,
    "MEETING_ID": String,
    "NOTICE_DATE": String,
    "NAME_OF_CONCILIATOR": String,
    "DATE_OF_CONCILIATION": String,
    "TIMING_OF_CONCILIATION": String,
    "ShortUrl":String,
    "MessageId":String,
    "notificationType":String,
    pdfBuffer: Buffer,
    excelId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Excel", // Reference the Excel model
    },
});

const XLData = mongoose.model("XLData", xlDataSchema);

export default XLData;



// const xlDataSchema = new mongoose.Schema({
//     REF_NO: String,
//     DATE: Date,
//     ACCOUNT: String,
//     CARDNO: String,
//     FPR_NAME: String,
//     FPR_LD_LIN: String,
//     FPR_MOB: String,
//     EMBONAME: String,
//     ADDRESS1: String,
//     ADDRESS2: String,
//     CITY: String,
//     STATE: String,
//     PINCODE: String,
//     NNR: String,
//     "NEW_CURR BAL": String,
//     RISKCLASS: String,
//     BLOCK1: String,
//     BLOCK2: String,
//     "INT FLAG": String,
//     ZONE: String,
//     SENDER: String,
//     BKT: String,
//     MOBILEPHONE_HOME: String,
//     TREGGER: String,
//     ACTIVITY: String,
//     STAGE: String,
//     "Email Id": String,
//     "REQUEST RAISE BY": String,
//     Region: String,
//     Language: String,
//     "Opertaional Status": String,
//     "Short Link": String,
//     "SMS Status": String,
//     "EMAIL STATUS": String,
//     NoticeType: String,
//     excelId: {
//         type: mongoose.Schema.Types.ObjectId,
//         ref: "Excel", // Reference the Excel model
//     },
// });

